---
- name: update waf to use python3
  replace:
    path: "{{ install_directory }}/waf"
    regexp: "python"
    replace: "python3"

- name: configure build
  command: "{{ item }}"
  args:
    chdir: "{{ install_directory }}"
  with_items:
    - ./waf configure
    - ./waf build
  become: false

- name: install
  command: "cp {{ install_directory }}/build/libf3kdb.so /usr/local/lib/"
  become: true
