---
- name: Update paths and packages
  hosts: default
  roles:
    - common

- name: Install dependencies
  hosts: default
  roles:
    - zimg
    - ffmpeg

- name: Install vapoursynth
  hosts: default
  roles:
    - vapoursynth
