---
- set_fact:
    repo: https://github.com/EleonoreMizo/fmtconv
    tag: "{{ fmtconv_tag }}"
    install_directory: "{{ home_directory }}/installs/fmtconv"

- name: update git status
  import_tasks: ../../git/tasks/main.yaml

- name: install fmtconv
  import_tasks: install_fmtconv.yaml
