---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
    - libtool
    - pkg-config
    - build-essential
    - python3-dev
    - git
  become: true
