# https://github.com/hashicorp/vagrant/issues/8878
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

Vagrant.configure(2) do |config|
   # Provision box per Packer instructions in readme
   config.vm.box = "ubuntu1804-desktop"
   config.vm.boot_timeout = 600

   # https://www.vagrantup.com/docs/vagrantfile/machine_settings.html
	config.vm.provider 'virtualbox' do |vb|
      vb.name = "vapoursynth-vbox"
      vb.gui = true
		vb.customize ["modifyvm", :id, "--cpus", 4]
		vb.customize ["modifyvm", :id, "--memory", 4096]
		vb.customize ["modifyvm", :id, "--vram", "256"]
		vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
		vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
		vb.customize ["modifyvm", :id, "--pae", "off"]
      #for vbox 6.x need to enable clipboard-mode, 5.x uses clipboard
      # https://github.com/hashicorp/vagrant/issues/11288
      #vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
      vb.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
	end

 # https://superuser.com/questions/1160025/how-to-solve-ttyname-failed-inappropriate-ioctl-for-device-in-vagrant/1277604#1277604
  	# zimg dependencies
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-zimg-libs.sh'
	   s.name = 'zimg-libs'
	   s.privileged = true
	end

  	# zimg installation
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-zimg.sh'
	   s.name = 'zimg'
	   s.privileged = false
	end
	
  	# ffmpeg installation
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-ffmpeg.sh'
	   s.name = 'ffmpeg'
	   s.privileged = false
	end	

   # vsynth dependencies
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-vsynth-libs.sh'
	   s.name = 'vsynth-libs'
	   s.privileged = true
	end

   # vsynth installation
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-vsynth.sh'
	   s.name = 'vsynth'
	   s.privileged = false
	end

   # vsedit dependencies
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-vsedit-libs.sh'
	   s.name = 'vsedit-libs'
	   s.privileged = true
	end

   # vsedit installation
   config.vm.provision "file", source: "./vsedit.desktop", destination: "~/vsedit.desktop"
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-vsedit.sh'
	   s.name = 'vsedit'
	   s.privileged = false
	end

   # d2vwitch dependencies
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-d2vwitch-libs.sh'
	   s.name = 'd2vwitch-libs'
	   s.privileged = true
	end

   # d2vwitch installation
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-d2vwitch.sh'
	   s.name = 'd2vwitch'
	   s.privileged = false
	end

   # d2vwitch installation
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-d2vsource.sh'
	   s.name = 'd2vsource'
	   s.privileged = false
	end

   # install vapoursynth scripts
	config.vm.provision :shell do |s|
	   s.path = 'scripts/install-vsscripts.sh'
	   s.name = 'vsscripts'
	   s.privileged = false
	end

end
