---
- name: Update local git repo
  ansible.builtin.git:
    repo: https://github.com/vapoursynth/vapoursynth.git
    dest: "{{ install_directory }}"
    version: "{{ vapoursynth_desired_version }}"

- name: Build steps
  shell: "{{ item }}"
  args:
    chdir: "{{ install_directory }}"
  with_items:
    - ./autogen.sh
    - ./configure
    - make clean
    - make -j $(nproc)
  become: false

- name: Install binary
  command: make install
  args:
    chdir: "{{ install_directory }}"
  become: true

# Required for some plugins to load.
- name: make config directory
  file:
    path: "{{ home_directory }}/.config/vapoursynth"
    state: directory
  become: false

- name: create vapoursynth.conf
  shell: echo 'UserPluginDir=/usr/local/lib' | tee --append "{{ home_directory }}/.config/vapoursynth/vapoursynth.conf"

- name: ldconfig
  command: ldconfig
  become: true
