---
- name: Update package cache
  apt:
    update_cache: yes
  become: true

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
    - libtool
    - pkg-config
    - build-essential
  become: true
