# https://github.com/hashicorp/vagrant/issues/8878
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

Vagrant.configure(2) do |config|
   # Provision box per Packer instructions in readme
   config.vm.box = "ubuntu1804-desktop"
   config.vm.boot_timeout = 600

   # # https://www.vagrantup.com/docs/vagrantfile/machine_settings.html
   # config.vm.provider 'virtualbox' do |vb|
   #    vb.name = "vsynth-ansible-vbox"
   #    vb.gui = true
   #    vb.customize ["modifyvm", :id, "--cpus", 4]
   #    vb.customize ["modifyvm", :id, "--memory", 4096]
   #    vb.customize ["modifyvm", :id, "--vram", "256"]
   #    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
   #    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
   #    vb.customize ["modifyvm", :id, "--pae", "off"]
   #    vb.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
   #    vb.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
   # end

  # zimg installation
	config.vm.provision "ansible" do |ans|
	   ans.playbook  = 'playbook.yml'
     ans.inventory_path = 'hosts'
	   ans.verbose   = 'v'
	end

  # 	# ffmpeg installation
	# config.vm.provision :shell do |s|
	#    s.path = 'scripts/install-ffmpeg.sh'
	#    s.name = 'ffmpeg'
	#    s.privileged = false
	# end
  #
  #  # vsynth installation
	# config.vm.provision :shell do |s|
	#    s.path = 'scripts/install-vsynth.sh'
	#    s.name = 'vsynth'
	#    s.privileged = false
	# end
  #
  #  # vsedit installation
  #  #config.vm.provision "file", source: "./vsedit.desktop", destination: "~/vsedit.desktop"
	# config.vm.provision :shell do |s|
	#    s.path = 'scripts/install-vsedit.sh'
	#    s.name = 'vsedit'
	#    s.privileged = false
	# end
  #
  #  # d2vwitch installation
	# config.vm.provision :shell do |s|
	#    s.path = 'scripts/install-d2vwitch.sh'
	#    s.name = 'd2vwitch'
	#    s.privileged = false
	# end
  #
  #  # d2vsource installation
	# config.vm.provision :shell do |s|
	#    s.path = 'scripts/install-d2vsource.sh'
	#    s.name = 'd2vsource'
	#    s.privileged = false
	# end
  #
  #  # install vapoursynth plugins
	# config.vm.provision :shell do |s|
	#    s.path = 'scripts/install-plugins.sh'
	#    s.name = 'plugins'
	#    s.privileged = false
	# end
  #
  #  # install vapoursynth scripts
	# config.vm.provision :shell do |s|
	#    s.path = 'scripts/install-vsscripts.sh'
	#    s.name = 'vsscripts'
	#    s.privileged = false
	# end
  #
  #  # install test files
	# config.vm.provision :shell do |s|
	#    s.path = 'scripts/install-test-files.sh'
	#    s.name = 'test-files'
	#    s.privileged = false
	# end

end
