# https://github.com/hashicorp/vagrant/issues/8878
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

Vagrant.configure(2) do |config|
   # Provision box per Packer instructions in readme
   config.vm.box = "ubuntu1804-desktop"
   config.vm.boot_timeout = 600

   # https://www.vagrantup.com/docs/vagrantfile/machine_settings.html
   config.vm.provider 'virtualbox' do |vb|
      vb.name = "vapoursynth-ansible-bionic"
      vb.gui = true
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--vram", "256"]
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
      vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
      vb.customize ["modifyvm", :id, "--pae", "off"]
      vb.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
      vb.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
   end

  # Playbook contains installation instructions for dependencies, vapoursynth
  # plugins, utilities and scripts.
	config.vm.provision "ansible" do |ans|
	   ans.playbook  = 'ansible/install-all.yml'
     ans.inventory_path = 'ansible/hosts'
	   ans.verbose   = 'v'
	end

end
