---
- name: autogen configure make
  shell: "{{ item }}"
  args:
    chdir: "{{ install_directory }}"
  with_items:
    - ./autogen.sh
    - ./configure --enable-shared
    - make clean
    - make -j $(nproc)
  become: false

- name: make install
  command: make install
  args:
    chdir: "{{ install_directory }}"
  become: true

# Required for some plugins to load.
- name: make config directory
  file:
    path: "{{ home_directory }}/.config/vapoursynth"
    state: directory
  become: false

- name: create vapoursynth.conf
  shell: echo 'UserPluginDir=/usr/local/lib' | tee --append "{{ home_directory }}/.config/vapoursynth/vapoursynth.conf"

- name: ldconfig
  command: ldconfig
  args:
    chdir: "{{ install_directory }}"
  become: true
