---
- name: vapoursynth - autogen configure make
  command: "{{ item }}"
  args:
    chdir: "{{ install_directory }}"
  with_items:
    - ./autogen.sh
    - ./configure
    - make clean
    - make
  become: false

- name: vapoursynth - make install
  command: make install
  args:
    chdir: "{{ install_directory }}"
  become: true

- name: vapoursynth - make config directory
  file:
    path: "{{ home_directory }}/.config/vapoursynth"
    state: directory
  become: false

- name: set PYTHONPATH
  shell: echo 'export PYTHONPATH=/usr/local/lib/python3.6/site-packages/' | tee --append "{{ home_directory }}/.bashrc"

- name: create vapoursynth.conf
  shell: echo echo 'UserPluginDir=/usr/local/lib' | tee --append "{{ home_directory }}/.config/vapoursynth/vapoursynth.conf"

- name: update ld.so.conf path
  shell: echo 'include /usr/local/lib' | sudo tee --append /etc/ld.so.conf

- name: vapoursynth - ldconfig
  command: ldconfig
  args:
    chdir: "{{ install_directory }}"
  become: true
