---
- name: Update package cache
  apt:
    update_cache: yes
  become: true

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
    - libtool
    - pkg-config
    - build-essential
    - python3-dev
    - git
    - cython3
    - python3-pip
  become: true

# This is necessary in ubuntu 18.04, as vapoursynth requires
# cython3 v0.29.14. 18.04 provides cython3 v0.26.1. Pip installs
# the correct version. This can be reviewed in a 20.04 branch.
# apt package is also necessary as pip isn't recognized by configure.
- name: pip3 install cython
  pip:
    name: cython
    extra_args: --user
    executable: pip3
  become: false
