---
- name: Update package cache
  apt:
    update_cache: yes
  become: true

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - automake
    - libtool
    - pkg-config
    - build-essential
    - python3-dev
    - git
    - cython3
    - python3-pip
  become: true

### Is this necessary?
- name: pip3 install cython
  pip:
    name: cython
    extra_args: --user
    executable: pip3
  become: false
