---
- name: install packages
  import_tasks: install_packages.yaml

- set_fact:
    repo: https://github.com/FFMS/ffms2.git
    tag: "{{ ffms2_tag }}"
    install_directory: "{{ home_directory }}/installs/ffms2"

- name: update git status
  import_tasks: ../../git/tasks/main.yaml

- name: install ffms2
  import_tasks: install_ffms2.yaml
