---
- name: install packages
  import_tasks: install_packages.yaml

- set_fact:
    repo: https://github.com/dubhater/vapoursynth-mvtools
    tag: "{{ mvtools_tag }}"
    install_directory: "{{ home_directory }}/installs/vapoursynth-mvtools"

- name: update git status
  import_tasks: ../../git/tasks/main.yaml

- name: install mvtools
  import_tasks: install_mvtools.yaml
