---
- name: make samples directory
  file:
    path: "{{ home_directory }}/samples"
    state: directory
  become: false

- name: install sample script
  copy:
    src: ../../../../sample-files/sample.vpy
    dest: "{{ home_directory }}/samples"
