---
- name: Build ffmpeg
  shell: "{{ item }}"
  args:
    chdir: "{{ install_directory }}"
  with_items:
    - ./configure --enable-gpl --enable-libx264 --enable-shared
    - make clean
    - make -j $(nproc)
  become: false

- name: Install ffmpeg binary
  command: make install
  args:
    chdir: "{{ install_directory }}"
  become: true

# ldconfig fixes inability to find libavdevice from /usr/local/lib
# path must be part of /etc/ld.so.conf
- name: ldconfig
  command: ldconfig
  become: true
