---
- name: Install ffmpeg packages
  import_tasks: install_packages.yaml
  when: install_state == "present"

- set_fact:
    install_directory: "{{ home_directory }}/installs/ffmpeg"

- name: Update local ffmpeg git repo
  ansible.builtin.git:
    repo: https://github.com/ffmpeg/ffmpeg.git
    dest: "{{ install_directory }}"
    version: "{{ ffmpeg_desired_version }}"

- name: Install ffmpeg
  import_tasks: install_ffmpeg.yaml
  when: install_state == "present"

- name: Remove ffmpeg
  import_tasks: remove_ffmpeg.yaml
  when: install_state == "absent"
