---
- name: what ffmpeg version is currrently installed?
  shell: ffmpeg -version | sed -n 1p | cut -d " " -f 3
  register: ffmpeg_current_version
  ignore_errors: True

# - debug:
#     var: '"not found" in ffmpeg_current_version.stderr'
- debug:
    var: ffmpeg_desired_version > ffmpeg_current_version.stdout

- name: install latest ffmpeg
  block:
    - name: install packages
      import_tasks: install_packages.yaml

    - set_fact:
        repo: https://github.com/ffmpeg/ffmpeg.git
        tag: "{{ ffmpeg_desired_version }}"
        install_directory: "{{ home_directory }}/installs/ffmpeg"

    - name: update git status
      import_tasks: ../../git/tasks/main.yaml

    - name: install ffmpeg
      import_tasks: install_ffmpeg.yaml
  when: ffmpeg_desired_version > ffmpeg_current_version.stdout
#  when: (ffmpeg_desired_version > ffmpeg_current_version.stdout or '"not found" in ffmpeg_current_version.stderr')
