---
- name: make
  command: "{{ item }}"
  args:
    chdir: "{{ install_directory }}"
  with_items:
    - make X86=1
  become: false

- name: install
  command: cp nnedi3_weights.bin vsznedi3.so /usr/local/lib/
  args:
    chdir: "{{ install_directory }}"
  become: true
