---
- name: autogen configure make
  shell: "{{ item }}"
  args:
    chdir: "{{ install_directory }}"
  with_items:
    - ./autogen.sh
    - ./configure
    - make clean
    - make -j $(nproc)
  become: false

- name: make install
  command: make install
  args:
    chdir: "{{ install_directory }}"
  become: true
