---
- name: install packages
  import_tasks: install_packages.yaml

- set_fact:
    repo: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-BM3D
    tag: "{{ bm3d_tag }}"
    install_directory: "{{ home_directory }}/installs/VapourSynth-BM3D"

- name: update git status
  import_tasks: ../../git/tasks/main.yaml

- name: install bm3d
  import_tasks: install_bm3d.yaml
