---
- name: configure make
  command: "{{ item }}"
  args:
    chdir: "{{ install_directory }}"
  with_items:
    - ./configure
    - make clean
    - make
  become: false

- name: make install
  command: make install
  args:
    chdir: "{{ install_directory }}"
  become: true
