---
# 6/6/2020: put this here instead of ~/.bashrc so it will work for things other than bash.
# pythonpath is required for vspipe and vsedit to find vapoursynth and scripts
- name: is python path set?
  shell: "grep {{ pythonpath }} /etc/environment"
  register: python_path_set
  ignore_errors: True

- debug:
    var: python_path_set.stdout

- debug:
    var: "'{{ pythonpath }}' in python_path_set.stdout"

- name: Conditionally set PYTHONPATH
  block:
    - name: set PYTHONPATH
      shell: echo 'PYTHONPATH="{{ pythonpath }}"' | sudo tee --append "/etc/environment"
  when: "'{{ pythonpath }}' not in python_path_set.stdout"

# ld.so.conf is required so vapoursynth can find plugins.
- name: is ld_so_conf set?
  shell: 'grep /usr/local/lib /etc/ld.so.conf'
  register: ld_so_conf_set
  ignore_errors: True

- debug:
    var: ld_so_conf_set.stdout

- debug:
    var: "'/usr/local/lib' in ld_so_conf_set.stdout"

- name: Conditionally set ld_so_conf
  block:
    - name: update ld_so_conf path
      shell: "echo 'include /usr/local/lib' | sudo tee --append '/etc/ld.so.conf'"
  when: "'/usr/local/lib' not in ld_so_conf_set.stdout"
