---
- name: Create a file to set the pythonpath variable
  become: yes
  ansible.builtin.file:
    dest: /etc/environment.d/vapoursynth.conf
    state: absent

# this is required for removing git repos downstream
- name: where is your home directory?
  shell: 'echo $HOME'
  register: home_shell

- set_fact:
    home_directory: "{{ home_shell.stdout }}"

- debug:
    var: home_directory