---
- name: Create a file to set the pythonpath variable
  become: yes
  ansible.builtin.copy:
    dest: /etc/environment.d/vapoursynth.conf
    content: |
      PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}/usr/local/lib/python3.12/site-packages"
    mode: '0644'

# placing /usr/local/lib in ld.so.conf is required so vapoursynth can find plugins.
- name: is ld_so_conf set?
  shell: 'grep /usr/local/lib /etc/ld.so.conf'
  register: ld_so_conf_set
  ignore_errors: True

- debug:
    var: ld_so_conf_set.stdout

- name: Conditionally set ld_so_conf
  block:
    - name: update ld_so_conf path
      shell: "echo 'include /usr/local/lib' | tee --append '/etc/ld.so.conf'"
      become: true
  when: "'/usr/local/lib' not in ld_so_conf_set.stdout"

- name: where is your home directory?
  shell: 'echo $HOME'
  register: home_shell

- set_fact:
    home_directory: "{{ home_shell.stdout }}"

- debug:
    var: home_directory
