---
- debug:
    var: packages_checked

- name: Upgrade packages
  when: packages_checked != true
  block:
    - name: Update package cache
      apt:
        update_cache: yes
      become: true
    - name: Upgrade all packages
      apt:
        upgrade: dist
      become: true
    - name: Remove unused dependencies
      apt:
        autoremove: yes
      become: true

- name: Set variable so we don't do this again
  set_fact:
    packages_checked: true

