---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - autoconf
    - automake
    - libtool
    - pkg-config
    - build-essential
    - libavformat-dev
    - libavcodec-dev
    - qt5-default
    - meson
    - ninja-build
  become: true
