Vagrant.configure(2) do |config|
	config.vm.box = "boxcutter/ubuntu1604-desktop"
	config.vm.box_version = "17.0907.1"
    #config.vm.box = "ubuntu/xenial64"
   	config.vm.boot_timeout = 600

	config.vm.provider 'virtualbox' do |vb|
    	vb.name = "vsynth-dev-sources"
		vb.gui = true
		vb.customize [
			"modifyvm", :id,
			"--cpus", 2,
			"--memory", 4096,
			"--vram", "64",
			"--cableconnected1", "on",
			"--accelerate3d", "off",
			"--pae", "off"
		]
	end
   	
	config.vm.provision :shell do |s|
		s.path = 'provision.sh'
	end
   	
	#config.vm.synced_folder '.', '/home/vagrant'

end
